/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aplikasishop;

import javafx.application.Application;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.scene.text.Font;
import javafx.scene.text.FontWeight;
import javafx.scene.text.Text;
import javafx.stage.Stage;

public class App extends Application {
    private Stage primaryStage;
    
    Pesanan pesanan1 = new Pesanan("Burger",25000);
    Pesanan pesanan2 = new Pesanan("Takoyaki",20000);
    Pesanan pesanan3 = new Pesanan("Pizza",50000);
    Pesanan pesanan4 = new Pesanan("Kentang Goreng", 10000);

    public static void main(String[] args) {
        launch(args);
    }
    @Override
    public void start(Stage primaryStage) {
        this.primaryStage = primaryStage;
        primaryStage.setTitle("FoodieGo");
        primaryStage.setScene(createHomePage());
        primaryStage.show();
    }
    // Halaman Utama (Home Page)
    private Scene createHomePage() {
    // Gambar(Logo) Aplikasi
        Image FoodieGo = new Image("./FoodieGo.jpeg");
        ImageView foodieGoView = new ImageView(FoodieGo);
        foodieGoView.setFitWidth(200);
        foodieGoView.setFitHeight(200);
    // Tombol Masuk
        Button loginButton = new Button("Masuk");
        loginButton.setStyle("-fx-background-color: black; -fx-text-fill: white;");
        loginButton.setOnAction(e -> {
            primaryStage.setScene(createLoginPage());
        });
    // Penyatuan Secara vertikal
        VBox layout = new VBox(0);
        layout.getChildren().addAll(foodieGoView, loginButton);
        layout.setAlignment(Pos.CENTER);
        layout.setStyle("-fx-background-color: #FAF2E9; -fx-padding:20px");

        BorderPane pane = new BorderPane();
        pane.setCenter(layout);
        return new Scene(pane, 300, 500);
    }
    // Halaman ke dua (Login Page)
    private Scene createLoginPage() {
        Text loginTitle = new Text("Halaman Login");
        loginTitle.setFont(Font.font("Arial", FontWeight.BOLD, 20));

        Label usernameLabel = new Label("Username:");
        TextField usernameField = new TextField();
        Label passwordLabel = new Label("Password:");
        PasswordField passwordField = new PasswordField();
    // Tombol Login
        Button loginButton = new Button("Login");
        loginButton.setStyle("-fx-background-color: black; -fx-text-fill: white;");
        loginButton.setOnAction(e -> {
            String username = usernameField.getText();
            String password = passwordField.getText();
            // Validasi ketentuan username dan password
            boolean isValid = validateUsername(username) && validatePassword(password);
            if (isValid) {
                primaryStage.setScene(createCategorySelectionPage());
            } else {
                // Tampilkan pesan kesalahan login
                Alert alert = new Alert(Alert.AlertType.ERROR);
                alert.setTitle("Error");
                alert.setHeaderText("Login Gagal");
                alert.setContentText("Username atau password tidak valid!");
                alert.showAndWait();
            }
        });
    // Tombol Kembali
        Button backButton = new Button("Kembali");
        backButton.setStyle("-fx-background-color: black; -fx-text-fill: white;");
        backButton.setOnAction(e -> {
            primaryStage.setScene(createHomePage());
        });
        VBox layout = new VBox(40);
        layout.getChildren().addAll(loginTitle, usernameLabel, usernameField, passwordLabel, passwordField, loginButton, backButton);
        layout.setAlignment(Pos.CENTER);
        layout.setStyle("-fx-background-color: #FAF2E9; -fx-padding:20px");

        BorderPane pane = new BorderPane();
        pane.setCenter(layout);
        return new Scene(pane, 300, 500);
    }
    // Halaman  ke tiga (Pilihan Kategori)
    private Scene createCategorySelectionPage() {
        Text categoryTitle = new Text("Pilih Kategori");
        categoryTitle.setFont(Font.font("Arial", FontWeight.BOLD, 20));

        Button makanan = new Button("MAKANAN");
        makanan.setStyle("-fx-background-color: black; -fx-text-fill: white;");
        makanan.setOnAction(e -> {
            primaryStage.setScene(createFoodSelectionPage());
        });
        Button minuman = new Button("MINUMAN");
        minuman.setStyle("-fx-background-color: black; -fx-text-fill: white;");
        minuman.setOnAction(e -> {
            primaryStage.setScene(createDrinkSelectionPage());
        });
        Button backButton = new Button("Kembali");
        backButton.setStyle("-fx-background-color: black; -fx-text-fill: white;");
        backButton.setOnAction(e -> {
            primaryStage.setScene(createHomePage());
        });
        VBox layout = new VBox(20);
        layout.getChildren().addAll(categoryTitle,makanan,minuman, backButton);
        layout.setAlignment(Pos.CENTER);
        layout.setStyle("-fx-background-color: #FAF2E9; -fx-padding:20px");

        BorderPane pane = new BorderPane();
        pane.setCenter(layout);
        return new Scene(pane, 300, 500);
    }
    // Halaman ke 4 (Pilihan Makanan) 
    private Scene createFoodSelectionPage() {
        Text foodTitle = new Text("Pilih Makanan");
        foodTitle.setFont(Font.font("Arial", FontWeight.BOLD, 20));
        // Daftar makanan
        Image Burger = new Image("./Burger.jpg");
        ImageView burgerView = new ImageView(Burger);
        burgerView.setFitWidth(75);
        burgerView.setFitHeight(75);

        Text BurgerName = new Text("BURGER");
        BurgerName.setFont(Font.font("Arial", FontWeight.BOLD, 10));

        Text hargaBurger = new Text("Rp 25.000");
        hargaBurger.setFont(Font.font("Arial", FontWeight.BOLD, 10));
        
        Image Takoyaki = new Image("./Takoyaki.jpg");
        ImageView TakoyakiView = new ImageView(Takoyaki);
        TakoyakiView.setFitWidth(75);
        TakoyakiView.setFitHeight(75);

        Text TakoyakiName = new Text("TAKOYAKI");
        TakoyakiName.setFont(Font.font("Arial", FontWeight.BOLD, 10));

        Text hargaTakoyaki = new Text("Rp 20.000");
        hargaTakoyaki.setFont(Font.font("Arial", FontWeight.BOLD, 10));

        Image Pizza = new Image("./Pizza.jpg");
        ImageView pizzaView = new ImageView(Pizza);
        pizzaView.setFitWidth(75);
        pizzaView.setFitHeight(75);

        Text PizzaName = new Text("PIZZA");
        PizzaName.setFont(Font.font("Arial", FontWeight.BOLD, 10));

        Text hargaPizza = new Text("Rp 50.000");
        hargaPizza.setFont(Font.font("Arial", FontWeight.BOLD, 10));

        Image Kentang = new Image("./Kentang.jpg");
        ImageView KentangView = new ImageView(Kentang);
        KentangView.setFitWidth(75);
        KentangView.setFitHeight(75);

        Text KentangName = new Text("KENTANG GORENG");
        KentangName.setFont(Font.font("Arial", FontWeight.BOLD, 10));

        Text hargaKentang = new Text("Rp 10.000");
        hargaKentang.setFont(Font.font("Arial", FontWeight.BOLD, 10));


        Button backButton = new Button("Kembali");
        backButton.setStyle("-fx-background-color: black; -fx-text-fill: white;");
        backButton.setOnAction(e -> {
            primaryStage.setScene(createCategorySelectionPage());
        });

        Label JumlahBurger = new Label("Jumlah:");
        TextField inpBurger = new TextField();
        inpBurger.setText("0");
        // inpBurger.setOnAction(e -> {
        //     String quantity = inpBurger.getText();
        //     int quan = Integer.parseInt(quantity);
        //     pesanan1.setJumlah(quantity1);
        //     primaryStage.setScene(createOrderSummaryPage());
        // });
        inpBurger.setStyle("-fx-padding:1px");

        VBox vbox1 =new VBox(10);
        vbox1.getChildren().addAll(BurgerName,hargaBurger);
        vbox1.setAlignment(Pos.CENTER);

        HBox hbox1 = new HBox(10);
        hbox1.getChildren().addAll(burgerView,vbox1);
        hbox1.setAlignment(Pos.CENTER);

        VBox inp1 = new VBox(10);
        inp1.getChildren().addAll(JumlahBurger,inpBurger);

        HBox gabungan1 = new HBox(20);
        gabungan1.getChildren().addAll(hbox1,inp1);

        
        Label JumlahTakoyaki = new Label("Jumlah:");
        TextField inpTakoyaki = new TextField();
        inpTakoyaki.setText("0");
        // inpTakoyaki.setOnAction(e -> {
        //     String quantity = inpTakoyaki.getText();
        //     int quantity1 = Integer.parseInt(quantity);
        //     pesanan2.setJumlah(quantity1);
        // });
        inpTakoyaki.setStyle("-fx-padding:1px");

        VBox vbox2 =new VBox(10);
        vbox2.getChildren().addAll(TakoyakiName,hargaTakoyaki);
        vbox2.setAlignment(Pos.CENTER);

        HBox hbox2 = new HBox(10);
        hbox2.getChildren().addAll(TakoyakiView,vbox2);
        hbox2.setAlignment(Pos.CENTER);

        VBox inp2 = new VBox(10);
        inp2.getChildren().addAll(JumlahTakoyaki, inpTakoyaki);

        HBox gabungan2 = new HBox(20);
        gabungan2.getChildren().addAll(hbox2,inp2);

        Label JumlahPizza = new Label("Jumlah:");
        TextField inpPizza = new TextField();
        inpPizza.setText("0");
        // inpPizza.setOnAction(e -> {
        //     String quantity = inpPizza.getText();
        //     int quantity1 = Integer.parseInt(quantity);
        //     pesanan3.setJumlah(quantity1);
        // });
        inpPizza.setStyle("-fx-padding:1px");

        VBox vbox3 =new VBox(10);
        vbox3.getChildren().addAll(PizzaName,hargaPizza);
        vbox3.setAlignment(Pos.CENTER);

        HBox hbox3 = new HBox(10);
        hbox3.getChildren().addAll(pizzaView,vbox3);
        hbox3.setAlignment(Pos.CENTER);

        VBox inp3 = new VBox(10);
        inp3.getChildren().addAll(JumlahPizza,inpPizza);

        HBox gabungan3 = new HBox(20);
        gabungan3.getChildren().addAll(hbox3,inp3);

        Label JumlahKentang = new Label("Jumlah:");
        TextField inpKentang = new TextField();
        inpKentang.setText("0");
        // inpKentang.setOnAction(e -> {
        //     String quantity = inpKentang.getText();
        //     int quantity1 = Integer.parseInt(quantity);
        //     pesanan4.setJumlah(quantity1);
        // });
        inpKentang.setStyle("-fx-padding:1px");

        VBox vbox4 =new VBox(10);
        vbox4.getChildren().addAll(KentangName,hargaKentang);
        vbox4.setAlignment(Pos.CENTER);

        HBox hbox4 = new HBox(10);
        hbox4.getChildren().addAll(KentangView,vbox4);
        hbox4.setAlignment(Pos.CENTER);

        VBox inp4 = new VBox(10);
        inp4.getChildren().addAll(JumlahKentang,inpKentang);

        HBox gabungan4 = new HBox(20);
        gabungan4.getChildren().addAll(hbox4,inp4);

        Button tambahpesananButton = new Button("Tambah Pesanan");
        tambahpesananButton.setStyle("-fx-background-color: black; -fx-text-fill: white;");
        tambahpesananButton.setOnAction(e -> {
            String quantity = inpBurger.getText();
            int quantity1 = Integer.parseInt(quantity);
            pesanan1.setJumlah(quantity1);
            String quantit = inpTakoyaki.getText();
            int quantit1 = Integer.parseInt(quantit);
            pesanan2.setJumlah(quantit1);
            String quanti = inpPizza.getText();
            int quqnti1 = Integer.parseInt(quanti);
            pesanan3.setJumlah(quqnti1);
            String quanti2 = inpKentang.getText();
            int quan = Integer.parseInt(quanti2);
            pesanan4.setJumlah(quan);
            primaryStage.setScene(createOrderSummaryPage());
        });

        HBox Tombol1 = new HBox(30);
        Tombol1.getChildren().addAll(backButton,tambahpesananButton);

        VBox mainLayout = new VBox(10);
        mainLayout.getChildren().addAll(foodTitle,gabungan1,gabungan2, gabungan3, gabungan4,Tombol1);
        mainLayout.setAlignment(Pos.CENTER);
        mainLayout.setStyle("-fx-background-color: #FAF2E9; -fx-padding:20px");

        BorderPane pane = new BorderPane();
        pane.setCenter(mainLayout);

        return new Scene(pane, 300, 500);
    }


    // Halaman ke empat (Pilihan Minuman)
    private Scene createDrinkSelectionPage() {
        Text drinkTitle = new Text("Pilih Minuman");
        drinkTitle.setFont(Font.font("Arial", FontWeight.BOLD, 20));
        // Daftar minuman
        Image LemonTea = new Image("./Lemontea.jpg");
        ImageView lemonTeaView = new ImageView(LemonTea);
        lemonTeaView.setFitWidth(75);
        lemonTeaView.setFitHeight(75);

        Text LemonTeaName = new Text("LEMON TEA");
        LemonTeaName.setFont(Font.font("Arial", FontWeight.BOLD, 10));

        Text hargaLemontea = new Text("Rp 10.000");
        hargaLemontea.setFont(Font.font("Arial", FontWeight.BOLD, 10));

        Image BubbleTea = new Image("./Bubbletea.jpg");
        ImageView BubbleTeaView = new ImageView(BubbleTea);
        BubbleTeaView.setFitWidth(75);
        BubbleTeaView.setFitHeight(75);

        Text BubbleTeaName = new Text("BUBBLE TEA");
        BubbleTeaName.setFont(Font.font("Arial", FontWeight.BOLD, 10));

        Text hargaBubbleTea = new Text("Rp 15.000");
        hargaBubbleTea.setFont(Font.font("Arial", FontWeight.BOLD, 10));

        Image IceTea = new Image("./Icetea.jpg");
        ImageView IceTeaView = new ImageView(IceTea);
        IceTeaView.setFitWidth(75);
        IceTeaView.setFitHeight(75);

        Text IceTeaName = new Text("ICE TEA");
        IceTeaName.setFont(Font.font("Arial", FontWeight.BOLD, 10));

        Text hargaIceTea = new Text("Rp 5.000");
        hargaIceTea.setFont(Font.font("Arial", FontWeight.BOLD, 10));

        Image Mineral = new Image("./Mineralwater.jpg");
        ImageView MineralView = new ImageView(Mineral);
        MineralView.setFitWidth(75);
        MineralView.setFitHeight(75);

        Text MineralName = new Text("MINERAL WATER");
        MineralName.setFont(Font.font("Arial", FontWeight.BOLD, 10));

        Text hargaMineral = new Text("Rp 5.000");
        hargaMineral.setFont(Font.font("Arial", FontWeight.BOLD, 10));
   
        Button tambahpesananButton = new Button("Tambah Pesanan");
        tambahpesananButton.setStyle("-fx-background-color: black; -fx-text-fill: white;");
        tambahpesananButton.setOnAction(e -> {
            primaryStage.setScene(createOrderSummaryPage());
        });

        Button backButton = new Button("Kembali");
        backButton.setStyle("-fx-background-color: black; -fx-text-fill:white");
        backButton.setOnAction(e -> {
            primaryStage.setScene(createCategorySelectionPage());
        });

        Label Jumlahlemontea = new Label("Jumlah:");
        TextField inplemontea = new TextField();
        inplemontea.setStyle("-fx-padding:1px");

        VBox vbox5 =new VBox(10);
        vbox5.getChildren().addAll(LemonTeaName,hargaLemontea);
        vbox5.setAlignment(Pos.CENTER);

        HBox hbox5 = new HBox(10);
        hbox5.getChildren().addAll(lemonTeaView,vbox5);
        hbox5.setAlignment(Pos.CENTER);

        VBox inp5 = new VBox(10);
        inp5.getChildren().addAll(Jumlahlemontea,inplemontea);

        HBox gabungan5 = new HBox(20);
        gabungan5.getChildren().addAll(hbox5,inp5);

        Label JumlahBubbletea = new Label("Jumlah:");
        TextField inpBubbletea = new TextField();
        inpBubbletea.setStyle("-fx-padding:1px");

        VBox vbox6 =new VBox(10);
        vbox6.getChildren().addAll(BubbleTeaName,hargaBubbleTea);
        vbox6.setAlignment(Pos.CENTER);

        HBox hbox6 = new HBox(10);
        hbox6.getChildren().addAll(BubbleTeaView, vbox6);
        hbox6.setAlignment(Pos.CENTER);
   
        VBox inp6 = new VBox(10);
        inp6.getChildren().addAll(JumlahBubbletea,inpBubbletea);

        HBox gabungan6 = new HBox(20);
        gabungan6.getChildren().addAll(hbox6,inp6);

        Label JumlahIcetea = new Label("Jumlah:");
        TextField inpIcetea = new TextField();
        inpIcetea.setStyle("-fx-padding:1px");

        VBox vbox7 =new VBox(10);
        vbox7.getChildren().addAll(IceTeaName,hargaIceTea);
        vbox7.setAlignment(Pos.CENTER);

        HBox hbox7 = new HBox(10);
        hbox7.getChildren().addAll(IceTeaView, vbox7);
        hbox7.setAlignment(Pos.CENTER);
   
        VBox inp7 = new VBox(10);
        inp7.getChildren().addAll(JumlahIcetea,inpIcetea);

        HBox gabungan7 = new HBox(20);
        gabungan7.getChildren().addAll(hbox7,inp7);

        Label JumlahMineral = new Label("Jumlah:");
        TextField inpMineral = new TextField();
        inpMineral.setStyle("-fx-padding:1px");

        VBox vbox8 =new VBox(10);
        vbox8.getChildren().addAll(MineralName,hargaMineral);
        vbox8.setAlignment(Pos.CENTER);

        HBox hbox8 = new HBox(10);
        hbox8.getChildren().addAll(MineralView, vbox8);
        hbox8.setAlignment(Pos.CENTER);
   
        VBox inp8 = new VBox(10);
        inp8.getChildren().addAll(JumlahMineral,inpMineral);

        HBox gabungan8 = new HBox(20);
        gabungan8.getChildren().addAll(hbox8,inp8);

        HBox Tombol2 = new HBox(20);
        Tombol2.getChildren().addAll(backButton,tambahpesananButton);

        VBox mainLayout = new VBox(20);
        mainLayout.getChildren().addAll(drinkTitle,gabungan5, gabungan6,gabungan7, gabungan8,Tombol2);
        mainLayout.setAlignment(Pos.CENTER);
        mainLayout.setStyle("-fx-background-color: #FAF2E9; -fx-padding:20px");

        BorderPane pane = new BorderPane();
        pane.setCenter(mainLayout);

        return new Scene(pane, 300, 500);
    } 
    // Scene untuk menampilkan pesanan
    private Scene createOrderSummaryPage() {
        Text summaryTitle = new Text("Ringkasan Pesanan");
        summaryTitle.setFont(Font.font("Arial", FontWeight.BOLD, 20));
        Text titel1 = new Text("Daftar Pesanan Burger");
        titel1.setFont(Font.font("Arial", FontWeight.BOLD, 10));
        Text pes = new Text("Pesanan :" + pesanan1.nama);
        Text jum = new Text("Jumlah :" + pesanan1.Jumlah);
        Text har = new Text("Harga :" + pesanan1.Harga);
        VBox sc1= new VBox(10);
        sc1.getChildren().addAll(titel1,pes,jum,har);
        // System.out.println(pesanan1.Jumlah);
        Text titel2 = new Text("Daftar Pesanan Takoyaki");
        titel2.setFont(Font.font("Arial", FontWeight.BOLD, 10));
        Text pes2 = new Text("Pesanan :" + pesanan2.nama);
        Text jum2 = new Text("Jumlah :" + pesanan2.Jumlah);
        Text har2 = new Text("Harga :" + pesanan2.Harga);
        VBox sc2= new VBox(10);
        sc2.getChildren().addAll(titel2,pes2,jum2,har2);
        Text titel3 = new Text("Daftar Pesanan Pizza");
        titel3.setFont(Font.font("Arial", FontWeight.BOLD, 10));
        Text pes3 = new Text("Pesanan :" + pesanan3.nama);
        Text jum3 = new Text("Jumlah :" + pesanan3.Jumlah);
        Text har3 = new Text("Harga :" + pesanan3.Harga);
        VBox sc3= new VBox(10);
        sc3.getChildren().addAll(titel3,pes3,jum3,har3);
        Text titel4 = new Text("Daftar Pesanan Kentang");
        titel4.setFont(Font.font("Arial", FontWeight.BOLD, 10));
        Text pes4 = new Text("Pesanan :" + pesanan4.nama);
        Text jum4 = new Text("Jumlah :" + pesanan4.Jumlah);
        Text har4 = new Text("Harga :" + pesanan4.Harga);
        VBox sc4= new VBox(10);
        sc4.getChildren().addAll(titel4,pes4,jum4,har4);

        Button placeOrderButton = new Button("Pesan Sekarang");
        placeOrderButton.setStyle("-fx-background-color: black; -fx-text-fill: white;");
        placeOrderButton.setOnAction(e -> {
        // Logika untuk menyimpan pesanan 
        primaryStage.setScene(createCheckOutPage());
        });

        Button backButton = new Button("Pesan Lagi");
        backButton.setStyle("-fx-background-color: black; -fx-text-fill: white;");
        backButton.setOnAction(e -> primaryStage.setScene(createCategorySelectionPage()));

        HBox lay = new HBox(10);
        lay.getChildren().addAll(placeOrderButton,backButton);
        lay.setAlignment(Pos.CENTER);
        lay.setStyle("-fx-background-color: #FAF2E9; -fx-padding:20px");

        HBox g = new HBox(10);
        g.getChildren().addAll(sc1,sc2,sc3,sc4);
        g.setStyle("-fx-background-color: #FAF2E9; -fx-padding:20px");

        VBox g1 = new VBox(10);
        g1.getChildren().addAll(summaryTitle,g,lay);
        g1.setAlignment(Pos.CENTER);

        BorderPane pane = new BorderPane();
        pane.setCenter(g1);

        return new Scene(pane, 500, 500);
        
    }
    private Scene createCheckOutPage() {
        Text checkOut = new Text("BIL PESANAN");
        checkOut.setFont(Font.font("Arial", FontWeight.BOLD, 20));

        Label[] totals = new Label[4];
        totals[0] = new Label("Total keseluruhan pesanan : " + pesanan1.totalHarga);
        totals[1] = new Label("Total keseluruhan pesanan : " + pesanan2.totalHarga);
        totals[2] = new Label("Total keseluruhan pesanan : " + pesanan3.totalHarga);
        totals[3] = new Label("Total keseluruhan pesanan : " + pesanan4.totalHarga);
        VBox tot = new VBox(10);
        // label.getChildren().addAll();
        for (Label total : totals) {
            if (!total.getText().equals("Total keseluruhan pesanan :  0")){
                tot.getChildren().add(total);
            }             
        }
        Button Done = new Button("Selesai");
        Done.setStyle("-fx-background-color: black; -fx-text-fill: white;");
        Done.setOnAction(e -> {
        // Logika untuk menyimpan pesanan dan menampilkan ucapan terima kasih
        primaryStage.setScene(createThankYouPage());
        });

        VBox bil = new VBox(20);
        bil.getChildren().addAll(checkOut,tot,Done);
        bil.setAlignment(Pos.CENTER);
        bil.setStyle("-fx-background-color: #FAF2E9; -fx-padding: 20px");


        BorderPane pane = new BorderPane();
        pane.setCenter(bil);
        return new Scene(pane,300,500);
        
    }      
    private Scene createThankYouPage() {
        Text thankYouText = new Text("Terima kasih atas pesanan Anda!");
        thankYouText.setFont(Font.font("Arial", FontWeight.BOLD, 20));

        Button selesaiButton = new Button("Selesai");
        selesaiButton.setOnAction(e -> primaryStage.close());

        VBox layout = new VBox(20);
        layout.getChildren().addAll(thankYouText, selesaiButton);
        layout.setAlignment(Pos.CENTER);
        layout.setStyle("-fx-background-color: #FAF2E9; -fx-padding: 20px");

        BorderPane pane = new BorderPane();
        pane.setCenter(layout);

        return new Scene(pane, 300, 500);
    }   
    // Validasi Username
    private boolean validateUsername(String username) {
        // Misalnya, validasi bahwa username harus terdiri dari huruf dan angka saja
        return username.matches("^[a-zA-Z0-9]{1,8}+$");
    }
    // Validasi Password
    private boolean validatePassword(String password) {
        // password harus memiliki panjang minimal 8 karakter
        // dan mengandung kombinasi huruf besar, huruf kecil, dan angka
        return password.length() >= 8 && password.matches(".*[A-Z].*") && password.matches(".*[a-z].*") && password.matches(".*\\d.*");
    }
}
